// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0jsx4tM8RgeJFZKBjSiGNe2ngT_K-UhM',
    appId: '1:712953886358:web:f87b9234d3ceb1603534b7',
    messagingSenderId: '712953886358',
    projectId: 'insta-clone-d649c',
    authDomain: 'insta-clone-d649c.firebaseapp.com',
    storageBucket: 'insta-clone-d649c.appspot.com',
    measurementId: 'G-PYE71NG2KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHcoTBRPy_HL2UJAQ7kwwHINBwNKYEK1A',
    appId: '1:712953886358:android:50b2adc43cc3beaf3534b7',
    messagingSenderId: '712953886358',
    projectId: 'insta-clone-d649c',
    storageBucket: 'insta-clone-d649c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdxC_ntoQUAkQhgq6R-69W7FLgRibxOFQ',
    appId: '1:712953886358:ios:088d4afcde742bdb3534b7',
    messagingSenderId: '712953886358',
    projectId: 'insta-clone-d649c',
    storageBucket: 'insta-clone-d649c.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdxC_ntoQUAkQhgq6R-69W7FLgRibxOFQ',
    appId: '1:712953886358:ios:f9092caa152dac773534b7',
    messagingSenderId: '712953886358',
    projectId: 'insta-clone-d649c',
    storageBucket: 'insta-clone-d649c.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
